version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000

  mlflow:
    image: continuumio/miniconda3:latest
    container_name: mlflow
    command: >
      /bin/bash -c "
      conda create -n mlflow_env python=3.8 -y &&
      source /opt/conda/etc/profile.d/conda.sh &&
      conda activate mlflow_env &&
      pip install mlflow &&
      mlflow server --backend-store-uri sqlite:////mlflow/mlflow.db --default-artifact-root /mlflow/artifacts --host 0.0.0.0 --port 5000
      "
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./mlflow:/mlflow
    ports:
      - "5000:5000"
