services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prom/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  api_exporter:
    build:
      context: .
      dockerfile: ./prom/Dockerfile  # Utilisation du Dockerfile de l'exporteur
    container_name: api_exporter
    ports:
      - "8001:8001"
    volumes:
      - ./prom:/app

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000

  mlflow:
    image: continuumio/miniconda3:latest
    container_name: mlflow
    command: >
      /bin/bash -c "
      conda create -n mlflow_env python=3.8 -y &&
      source /opt/conda/etc/profile.d/conda.sh &&
      conda activate mlflow_env &&
      pip install mlflow &&
      mlflow server --backend-store-uri sqlite:////mlflow/mlflow.db --default-artifact-root /mlflow/artifacts --host 0.0.0.0 --port 5000
      "
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./mlflow:/mlflow
    ports:
      - "5000:5000"
