global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api_exporter:8001']  # L'exporteur exposera les métriques

  - job_name: 'api_service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:8000']  # Surveillance directe de l'API FastAPI
