name: Run Shell Script

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script
        run: ./infra/script.sh
        shell: bash
infra/.terraform/providers/registry.terraform.io/hashicorp/aws/5.81.0/darwin_arm64/terraform-provider-aws_v5.81.0_x5 (599.02 MB)